version: '3.8'
services:
  postgres:
    image: postgres:17
    container_name: postgres_prod
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: prod_beatsy
    ports:
      - "5434:5432"
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data

volumes:
  postgres_data_dev: