services:
  postgres:
    image: postgres:17
    container_name: postgres_tst
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: tst_beatsy
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_tst:/var/lib/postgresql/data

volumes:
  postgres_data_dev: