#  docker-compose -f docker-compose.dev.yml up -d
services:
  postgres:
    image: postgres:17
    container_name: postgres_dev
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: dev_beatsy
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data_dev: